### ISSUE TITLE
Question about pants and skirts

### ISSUE THREAD

**Issue by baoqiancherry** [enriccorona/SMPLicit#1]
Hi!

Thanks for your amazing work.
I am trying to display the dressed-mesh results with various pose and shape parameters instead of the T-pose.
It works fine for the upper clothes, hair, and shoes. However, for pants and skirts, it seems that they are upside down (second row in the Figure below). I don't know how to solve it.

![pants and skirts](https://user-images.githubusercontent.com/32625209/116026355-21a11c80-a685-11eb-8ab1-bf14a76a4cb7.png)

I just change the following code in example.py,
`pants_Z = np.zeros(18)`
`Zs = [pants_Z]`
`meshes = SMPLicit_layer.reconstruct(model_ids=[1], Zs=Zs,pose=loaded_pose,beta=loaded_shape)`

Thanks!

**Comment by enriccorona** [comment]
Hi, thanks for posting the issue.
There was a problem when posing lower clothes that should now work if you use the latest version. With this it works for me with these pants on a random posed human:

![image](https://user-images.githubusercontent.com/16597638/116139423-4a053700-a6d6-11eb-8600-e21306d6a626.png)

**Comment by baoqiancherry** [comment]
Works great now.
Thanks for the quick response.
