### ISSUE TITLE
question about supplement

### ISSUE THREAD

**Issue by yizheng-chen** [enriccorona/SMPLicit#16]
hi, thanks for your work.
In section 4.2 you said _see the Supp. Mat. for more details_, but there is no supplement in arxiv version. 
So can I have the supplements or the details about training? thanks!

**Comment by enriccorona** [comment]
Hi! This is the link to supplementary material: https://openaccess.thecvf.com/content/CVPR2021/supplemental/Corona_SMPLicit_Topology-Aware_Generative_CVPR_2021_supplemental.pdf
