### ISSUE TITLE
how to test on existing obj file?

### ISSUE THREAD

**Issue by akchain** [enriccorona/SMPLicit#2]
Hello, thanks for your great work.
I run all the examples and got expected results. 
And is it possible to load an existing SMPL obj file and do the similar clothes change to it? Thanks.

**Comment by enriccorona** [comment]
Hi, you need the SMPL parameters to generate clothing on that mesh. The shape parameters are needed to generate the cloth shape that best fits the body, and the pose allows the cloth to be posed along with the body.

So if you have pose and shape the SMPLicit layer will also generate the body mesh, you need to call the reconstruct() function with those pose and shape vectors.

If you don't have the SMPL parameters but your mesh was generated with SMPL (and has 6890 vertices), you can just fit SMPL to those vertices directly to get shape and pose. Let me know if that's the case and I can share some snippet to do that

**Comment by akchain** [comment]
Thanks  for your reply. 
I have a mesh generated with SMPL but not sure how to get these SMPL parameters. A piece of example code would help a lot. 
Besh wishes.

**Comment by enriccorona** [comment]
Sure. If your mesh is the direct output of some method that generates the SMPL model, the following code should work fine. If it's from SMPL-X, that mesh will have around 10K vertices and you can use this project to transfer them to SMPL vertices: https://github.com/vchoutas/smplx/tree/master/transfer_model. Anyway, this is a simple optimization that should be quite fast and work pretty much always:

```
from torch import nn
class OptimizationSMPL(nn.Module):
    def __init__(self, pose, trans):
        super(OptimizationSMPL, self).__init__()

        self.pose = nn.Parameter(pose.reshape(1, 72))
        self.beta = nn.Parameter((torch.rand(1, 10).cuda()-0.5/100))
        self.trans = nn.Parameter(trans.reshape(1, 3))

    def forward(self):
        return self.pose, self.beta, self.trans

parameters_smpl = OptimizationSMPL(torch.zeros(1, 72).cuda(), torch.zeros(1, 3).cuda()).cuda()
optimizer_smpl = torch.optim.Adam(parameters_smpl.parameters(), lr=1e-3)
iterations = 500
for i in range(iterations):
      pose, beta, trans = parameters_smpl.forward()
      vertices_smpl = self.SMPLicit_layer.SMPL_Layer.forward(theta=pose, beta=beta, get_skin=True)[0][0]
      vertices_smpl = vertices_smpl + trans
      loss = ((vertices_smpl - target_vertices)**2).mean()

      optimizer_smpl.zero_grad()
      loss.backward()
      optimizer_smpl.step()

final_pose, final_beta, final_trans = parameters_smpl.forward()
```

Best,
