### ISSUE TITLE
The model file seems to have been deleted from google drive

### ISSUE THREAD

**Issue by stranger-games** [enriccorona/SMPLicit#22]
Hi,

Thank you for this interesting great work.

I want to try it out, but it seems that it has been deleted.

https://drive.google.com/file/d/19plO4du6uXv8beTtEo0K3iYIyHu1YRHu/view?usp=sharing

Thanks for advance.

**Comment by ElonKou** [comment]
> 

I have the same question

**Comment by nyc1215** [comment]
I found another project which has SMPL neutral model.
Here are the download link : 
https://mailustceducn-my.sharepoint.com/:f:/g/personal/jby1993_mail_ustc_edu_cn/EqosuuD2slZCuZeVI2h4RiABguiaB4HkUBusnn_0qEhWjQ?e=c6r4KS

The project: `BCNet: Learning Body and Cloth Shape from A Single Image, ECCV 2020`
https://github.com/jby1993/BCNet/issues/2

**Comment by stranger-games** [comment]
@nyc1215 Thank you, but it seems like the link is not publicly shared.

**Comment by nyc1215** [comment]
@stranger-games The link is related with USTC in China, maybe you should use VPN.

**Comment by nyc1215** [comment]
@stranger-games  Sorry for that, I just changed a publicly shared link. Could you please try again?

**Comment by stranger-games** [comment]
> @stranger-games Sorry for that, I just changed a publicly shared link. Could you please try again?

@nyc1215  Working perfectly, thank you!

**Comment by sudo-vinnie** [comment]
Hi all,

I’m trying to run ClothWild and need the original SMPLicit cloth checkpoints + cluster files that were once hosted at the deleted Drive link (19plO4du6uXv8beTtEo0K3iYIyHu1YRHu).

Specifically, I’m looking for: upperclothes.pth, pants.pth, skirts.pth, shoes.pth, hair.pth, and the corresponding clusters_*.npy files.

If anyone who previously downloaded the bundle still has these files locally, would you be willing to share a mirror?

Thanks in advance!
