### ISSUE TITLE
Demo code for generating a 3D model from an image 

### ISSUE THREAD

**Issue by jizhu1023** [enriccorona/SMPLicit#4]
Could you provide the demo code for generating a 3D model from an input person image?

**Comment by enriccorona** [comment]
Hi, you can find the code for fitting SMPLicit under https://github.com/enriccorona/SMPLicit/tree/main/fit_SMPLicit
I updated this part with its own README and more instructions for running the code.

**Comment by GauravJaiKumar** [comment]
while running this code,
NameError: name 'render_image_projection' is not defined

**Comment by enriccorona** [comment]
Thanks, I cleaned the code a bit and removed this function, it's included now and should work. Could you try it again?

**Comment by jizhu1023** [comment]
@enriccorona thanks so much！ You have done great work.
