### ISSUE TITLE
No such file or directory: '/home/enric/cvpr21/SMPLicit/clusters/indexs_clusters_tshirt_smpl.npy'

### ISSUE THREAD

**Issue by izakharkin** [enriccorona/SMPLicit#9]
Hello,

Thank you for the code and the project, it looks awesome. 

Could you please help with an issue I face when running `python example.py`:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/enric/cvpr21/SMPLicit/clusters/indexs_clusters_tshirt_smpl.npy'
```

Looks that one needs some additional files to run the demo. Thank you in advance!

**Comment by sonnysorry** [comment]
I solved it with changing the path in SMPLcit_options.py file to my local path. 

you can find that .npy file in /SMPLicit/clusters/ directory.

**Comment by izakharkin** [comment]
Yes, thanks
